name: 'Publish to Repository'
description: 'Publishes a release to a remote repository'
inputs:
  token:
    description: 'The token to use for authentication'
    required: true
runs:
  using: node20
  main: dist/index.js
